name: Build Kernel on AArch64

on:
  workflow_dispatch:
    inputs:
      kernel_repo:
        description: 'Kernel repository to build'
        required: true
        default: 'Mayuri-Chan/android_kernel_xiaomi_gale-ksu'
      kernel_branch:
        description: 'Kernel branch to build'
        required: true
        default: 'master'
      kernelsu_repo:
        description: 'Kernelsu repository to build'
        required: true
        default: 'MayuriLabs/KernelSU'
      kernelsu_branch:
        description: 'Kernelsu branch to build'
        required: true
        default: 'main'
      kernelsu_defconfig:
        description: 'Kernelsu defconfig to build'
        required: true
        default: 'gale-ksu'
      kernelsu_susfs_repo:
        description: 'SUSFS repository to build'
        required: true
        default: 'MayuriLabs/KernelSU'
      kernelsu_susfs_branch:
        description: 'SUSFS branch to build'
        required: true
        default: 'susfs-main'
      kernelsu_susfs_defconfig:
        description: 'SUSFS defconfig to build'
        required: true
        default: 'gale-susfs'
      kernel_img:
        description: 'Kernel image name'
        required: false
        default: 'Image.gz'
      kernel_dtb:
        description: 'Kernel dtb name'
        required: false
        default: 'mediatek/mt6768.dtb'

jobs:
  build_ksu:
    runs-on: ubuntu-24.04-arm
    container:
      image: arm64v8/debian:bookworm
    steps:
      - name: Checkout script
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt update && apt upgrade -y
          apt install -y ccache wget bc build-essential make autoconf automake git bison pahole flex libssl-dev zip jq cpio

      - name: Clone kernel
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.kernel_repo }}
          path: kernel
          ref: ${{ github.event.inputs.kernel_branch }}
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-strict: "false"

      - name: Clone kernelsu
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.kernelsu_repo }}
          path: kernel/KernelSU
          ref: ${{ github.event.inputs.kernelsu_branch }}
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-strict: "false"

      - name: Write Config
        run: bash build.sh write_config
        env:
          DEFCONFIG: ${{ github.event.inputs.kernelsu_defconfig }}
          IS_SUSFS: 0
          KERNEL_IMG: ${{ github.event.inputs.kernel_img }}
          KERNEL_DTB: ${{ github.event.inputs.kernel_dtb }}

      - name: Setup Clang
        run: bash build.sh clang

      - name: Build Kernel
        run: bash build.sh kernel

      - name: Compress AnyKernel
        run: bash build.sh anykernel

      - name: Upload logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-logs-ksu
          path: Logs/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mayuri-kernel-ksu
          path: dist/

  build_susfs:
    runs-on: ubuntu-24.04-arm
    container:
      image: arm64v8/debian:bookworm
    steps:
      - name: Checkout script
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt update && apt upgrade -y
          apt install -y ccache wget bc build-essential make autoconf automake git bison pahole flex libssl-dev zip jq cpio

      - name: Clone kernel
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.kernel_repo }}
          path: kernel
          ref: ${{ github.event.inputs.kernel_branch }}
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-strict: "false"

      - name: Clone kernelsu
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.kernelsu_susfs_repo }}
          path: kernel/KernelSU
          ref: ${{ github.event.inputs.kernelsu_susfs_branch }}
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-strict: "false"

      - name: Write Config
        run: bash build.sh write_config
        env:
          DEFCONFIG: ${{ github.event.inputs.kernelsu_susfs_defconfig }}
          IS_SUSFS: 1
          KERNEL_IMG: ${{ github.event.inputs.kernel_img }}
          KERNEL_DTB: ${{ github.event.inputs.kernel_dtb }}

      - name: Setup Clang
        run: bash build.sh clang

      - name: Build Kernel
        run: bash build.sh kernel

      - name: Compress AnyKernel
        run: bash build.sh anykernel

      - name: Upload logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-logs-susfs
          path: Logs/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mayuri-kernel-susfs
          path: dist/
